/**
 * Build-time site constants. Editorial content (bio, statement, contact details,
 * images) lives in `src/content/profile/profile.json` so the artist can edit it
 * in the CMS without touching code.
 */
export const SITE = {
  url: 'https://kungadempatsang.com',
  name: 'Kunga Dempa Tsang',
  /** Default social-share image (generated by `pnpm icons`). */
  defaultOgImage: '/og-image.png',
} as const;

export const LOCALES = ['en', 'fr'] as const;
export type Locale = (typeof LOCALES)[number];
export const DEFAULT_LOCALE: Locale = 'en';
